extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/mem/*.bril'

[runs.baseline]
pipeline = ["bril2json", "brili -p {args}"]

[runs.myopt]
pipeline = ["awk '!/^[[:space:]]*free/'", "bril2json", "brili-gc -p {args}"]
